#!/usr/bin/env -S pkgx --quiet +nushell.sh nu@0.107.0

def main [ operation: string, input: string ] {
  if $operation == "install"  {
    return ( pkgx lua ~/.config/pkg/.bridges/go/main.lua $input )

  } else {
    print -e "__IMPL_DEFAULT"
    exit 1

  } | return $in;

}
