[opener]
play_sound = [
	{ run = 'alacritty mpv --no-video "$@"', orphan = true, for = "unix" },
]
view_document = [
	{ run = 'zathura "$@"', orphan = true, for = "unix" },
]
view_image = [
	{ run = 'qview "$@"', orphan = true, for = "unix" },
]
view_svg = [
  { run = 'nu -c "start \"$@\""', orphan = true, for = "unix" },
]
# ...
[open]
prepend_rules = [
	{ url = "*.mp3", use = "play_sound" },
	{ url = "*.pdf", use = "view_document" },
  { url = "*.png", use = "view_image" },
  { url = "*.jpg", use = "view_image" },
  { url = "*.jpeg", use = "view_image" },
  { url = "*.gif", use = "view_image" },
  { url = "*.svg", use = "view_svg" },
  { url = "*.webp", use = "view_image" },
  { url = "*.avi", use = "view_image" },
]


# prefetch
[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"
