# arrows in hjkl
CapsLock{J}   >> ArrowDown
CapsLock{K}   >> ArrowUp
CapsLock{H}   >> ArrowLeft
CapsLock{L}   >> ArrowRight

# capslock as escape and ctrl
CapsLock{Any} >> Control{Any}
CapsLock      >> Escape

# edit mappings
Meta{Y} >> PageUp
Meta{E} >> PageDown

# for my external keyboard
# [device = "BT5.0 KB"]
# Alt{Any} >> Meta{Any}
# Meta{Any} >> Alt{Any}
# Menu{Any} >> Meta{Any}

# cmds
# NOTE: u can use insha'Allah this: @forward-modifiers
# like so: @forward-modifiers Meta Shift{T} >> $(open -a Telegram)
Meta{Shift{T}}      >> $(open -a Telegram)
Meta{Shift{Enter}}  >> $(open -a Ghostty)
Meta{Shift{W}}      >> $(open -a qutebrowser)
Meta{Shift{O}}      >> $(open -a Obsidian)
Meta{Shift{E}}      >> $(/opt/pkg/cargo/neovide)
Meta{Shift{F}}      >> $(/Applications/Ghostty.app/Contents/MacOS/ghostty -e nu --login -c 'yazi ~')
