#!/usr/bin/env bash

shopt -s nullglob globstar

config_file=~/.config/scripts.conf
get_conf() {
  if [[ -f $config_file ]]; then
    cat $config_file | grep "$1" | cut -d ':' -f 2
  fi
}

menu=$(get_conf menu_list)
clipboard=$(get_conf clipboard_copy)

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg "$prefix"/**/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | "$menu" "$@")

[[ -n $password ]] || exit

if [[ -n $1 ]]; then
  pass show "$password" | grep "email:" | cut -d ':' -f 2 | "$clipboard"
elif [[ $1 == "mail" ]]; then
  pass show -c "$password";
fi

sleep 45

echo "" | "$clipboard"
