[tools]
dart = "latest"
flutter = "latest"
bun = "latest"
go = "latest"
java = "18" # NOTE: this should be before the android-sdk because it's a dependency
android-sdk = "latest"
cmake = "latest" # NOTE: this two should be before the clang because it's a dependency
python = "latest" # I'm not sure but I think that python is a dependency of ninja
ninja = "latest"
clang = "latest"
# make = "latest" # BUG: broken
just = "latest"
mask = "latest"
lima = "latest" # NOTE: a dependency of colima
colima = "latest"
git-lfs = "latest"
zig = "latest"
docker-cli = "latest"
docker-compose = "latest"
